import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { JsonSchema } from '@hozu/core/ir'
import type { EnvOutput, EnvVariable } from '../contract.ts'
import type { Loaded } from '../load.ts'

const RESERVED: [string, string][] = [
  ['PORT', 'hozu serve / hozu dev: the port (default 3000; hozu dev also uses PORT + 1 for the app)'],
  ['HOST', 'hozu serve: the interface to listen on'],
  [
    'SESSION_SECRET',
    'signs session cookies; production refuses to start without it when the app has sessions',
  ],
  ['NODE_ENV', "'production' turns on secure cookies and the production checks"],
  ['HOZU_TRANSFORM_CACHE', "'0' turns off the transform cache in .hozu/transform/"],
]

function variablesOf(
  side: 'server' | 'public',
  schema: JsonSchema | null,
  internal: Record<string, string>,
): EnvVariable[] {
  const s = (schema ?? {}) as {
    properties?: Record<string, { default?: unknown; description?: string }>
    required?: string[]
  }
  const mapped = Object.entries(internal)
  return Object.entries(s.properties ?? {}).map(([name, p]) => ({
    name,
    side,
    required: (s.required ?? []).includes(name) && p.default === undefined,
    default: p.default === undefined ? null : String(p.default),
    set: process.env[name] !== undefined && process.env[name] !== '',
    description: p.description ?? null,
    internal:
      side === 'public'
        ? (internal[name] ?? null)
        : (mapped.find(([, server]) => server === name)?.[0] ?? null),
  }))
}

/** `hozu env`: every variable the app reads, where it goes, and whether it is set now (ADR 0052). */
export function runEnv(loaded: Loaded, example: boolean): EnvOutput {
  const ir = loaded.build().ir
  const internal = ir.env?.internal ?? {}
  const variables = [
    ...variablesOf('server', ir.env?.server ?? null, internal),
    ...variablesOf('public', ir.env?.public ?? null, internal),
  ]
  const out: EnvOutput = {
    files: ir.env?.files ?? [],
    read: loaded.envFiles,
    variables,
    reserved: RESERVED.map(([name, purpose]) => ({ name, purpose, set: process.env[name] !== undefined })),
    example: null,
  }
  if (example) {
    const lines = ['# Generated by hozu env --example: every variable the app reads (ADR 0052).', '']
    for (const v of variables) {
      lines.push(
        `# ${v.side}${v.side === 'public' ? ' (sent to the browser)' : ''} · ${v.required ? 'required' : 'optional'}${v.internal ? ` · ${v.side === 'public' ? `internal: ${v.internal}` : `internal URL for ${v.internal}`}` : ''}${v.description ? ` · ${v.description}` : ''}`,
      )
      lines.push(`${v.name}=${v.side === 'public' && v.default !== null ? v.default : ''}`, '')
    }
    const file = join(dirname(loaded.path), '.env.example')
    writeFileSync(file, `${lines.join('\n').trimEnd()}\n`)
    out.example = '.env.example'
  }
  return out
}

export function describeEnv(out: EnvOutput): string {
  const lines = [
    `files: ${out.files.length ? out.files.map((f) => `${f}${out.read.includes(f) ? '' : ' (missing)'}`).join(', ') : 'none (project({ env: { files } }))'}`,
  ]
  for (const side of ['server', 'public'] as const) {
    const list = out.variables.filter((v) => v.side === side)
    if (!list.length) continue
    lines.push('', side === 'public' ? 'public (sent to the browser):' : 'server:')
    for (const v of list)
      lines.push(
        `  ${v.set ? '✔' : v.required ? '✖' : '·'} ${v.name}${v.required ? '' : v.default !== null ? ` = ${v.default}` : ' (optional)'}${v.internal ? (side === 'public' ? `  → server uses ${v.internal} when set` : `  internal URL for ${v.internal}`) : ''}`,
      )
  }
  lines.push('', 'reserved by Hozu:')
  for (const r of out.reserved) lines.push(`  ${r.set ? '✔' : '·'} ${r.name}  ${r.purpose}`)
  if (out.example) lines.push('', `wrote ${out.example}`)
  const missing = out.variables.filter((v) => v.required && !v.set)
  if (missing.length)
    lines.push('', `missing: ${missing.map((v) => v.name).join(', ')} (startup will refuse)`)
  return `${lines.join('\n')}\n`
}
