import { existsSync, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { basename, dirname, join } from 'node:path'

export const BEGIN = '<!-- hozu: generated by hozu skill; edits between these markers are replaced -->'
export const END = '<!-- /hozu -->'

const RUNNERS = ['pnpm exec', 'npx', 'yarn', 'bunx'] as const
type Runner = (typeof RUNNERS)[number]

export const TARGETS = [
  { guide: 'CLAUDE.md', skill: '.claude/skills/hozu', read: 'Use the `hozu` skill (`__SKILL__/SKILL.md`).' },
  {
    guide: 'AGENTS.md',
    skill: '.agents/skills/hozu',
    read: 'Read `__SKILL__/SKILL.md` before writing or changing any Hozu code.',
  },
] as const

const BROWSE =
  "__RUN__ hozu browse / --do 'click Save'     # real browser, no server: errors, widgets, text after steps\n"

export const GUIDE_07 = `# __NAME__

A web app built with Hozu (\`@hozu/*\`). Hozu is not in your training data.

## Before writing code
- __READ__
- Changing existing code: read \`__SKILL__/changing.md\` first.
- The files in \`__SKILL__/\` are the whole API. Do not read the framework source in \`node_modules/@hozu\`.

## The loop
\`\`\`
__RUN__ hozu add feature tasks --page / --with detail,toggle,filter,remove   # then edit the texts it lists
                                          # add auth to the list for sign-in and per-user data
__RUN__ hozu map                           # outline of the app with file:line, before a change
__RUN__ hozu check                         # after every change: types, rules, contracts
__RUN__ hozu check --update-lock           # only to accept a clean, intended behaviour change
__RUN__ hozu get / --select button --forms  # try pages without a server: text, attributes, forms
__RUN__ hozu post / --field title=Ship --next /   # submit a form like a browser
${BROWSE}\`\`\`
__NOTE__
## Rules
- After \`hozu add feature\`, do not print the generated files: edit the texts it lists; \`hozu map\` shows the rest.
- Apply the fix each diagnostic gives; do not work around a rule.
- Every behaviour change comes with a contract change.
- Do not edit \`__SKILL__/\`: \`__RUN__ hozu skill\` rewrites it for the installed Hozu version.
`

const KNOWN = [GUIDE_07, GUIDE_07.replace(BROWSE, '')]

const fill = (text: string, values: Record<string, string>) =>
  Object.entries(values).reduce((out, [key, value]) => out.replaceAll(`__${key}__`, value), text)

function filled(template: string, target: (typeof TARGETS)[number], name: string, runner: Runner) {
  const note =
    runner === 'pnpm exec'
      ? ''
      : `\nThe skill writes commands as \`pnpm exec …\`; in this app use \`${runner} …\`.\n`
  return fill(fill(template, { READ: target.read }), {
    NAME: name,
    RUN: runner,
    SKILL: target.skill,
    NOTE: note,
  })
}

export function currentGuide(): string {
  const require = createRequire(import.meta.url)
  return readFileSync(join(dirname(require.resolve('create-hozu')), '../templates/guide.md'), 'utf8')
}

export type BlockResult =
  | { kind: 'replaced' | 'marked' | 'written' | 'current'; code: string }
  | { kind: 'custom'; block: string }

/** The new Hozu block of a CLAUDE.md / AGENTS.md: between markers, or the whole file when it is a known template. */
export function migrateGuide(
  existing: string | null,
  target: (typeof TARGETS)[number],
  dir: string,
  runner: Runner,
  template = currentGuide(),
): BlockResult {
  const name = existing?.match(/^# (.+)$/m)?.[1] ?? basename(dir)
  const detected = RUNNERS.find((r) => existing?.includes(`${r} hozu check`)) ?? runner
  const block = `${BEGIN}\n${filled(template, target, name, detected).trimEnd()}\n${END}\n`
  if (existing === null) return { kind: 'written', code: block }
  const begin = existing.indexOf(BEGIN)
  const end = existing.indexOf(END)
  if (begin >= 0 && end > begin) {
    const code = existing.slice(0, begin) + block + existing.slice(end + END.length).replace(/^\n/, '')
    return { kind: code === existing ? 'current' : 'replaced', code }
  }
  for (const known of [...KNOWN, template])
    for (const r of RUNNERS)
      if (existing === filled(known, target, name, r)) return { kind: 'marked', code: block }
  return { kind: 'custom', block }
}

export const skillTargets = (dir: string) => TARGETS.filter((t) => existsSync(join(dir, t.skill)))
