// Code generated by hozu gen from the Hozu declarations. DO NOT EDIT.
// Change the declarations in TypeScript, then run hozu gen (ADR 0068).

package hozu

import (
	"context"
	"crypto/subtle"
	"encoding/json"
	"errors"
	"log"
	"net/http"
	"reflect"
	"strings"
)

// Fingerprint is the contract of one effect this file was generated from, or "" for another effect. Every call
// carries its effect's, so changing one declaration answers 409 for that effect alone.
func Fingerprint(effect string) string {
	switch effect {
	case "account.accounts":
		return "53d3ed3933cbba9a"
	case "account.me":
		return "b3d512da23c29498"
	case "account.signIn":
		return "948c96e255dad25a"
	case "account.signOut":
		return "83ecf475d2d715e6"
	case "notes.addNote":
		return "208c99e4dfbc205b"
	case "notes.listNotes":
		return "e4b13631d7555885"
	case "notes.notesApi":
		return "b97b81437df120c2"
	case "notes.pinNotes":
		return "986381f30c45785d"
	case "notes.removeNote":
		return "a93c356d5e3fd15a"
	case "notes.removeNotes":
		return "328e014cf81af1b6"
	case "notes.togglePin":
		return "665cb6debfd55200"
	}
	return ""
}

type Session struct {
	User string `json:"user"`
}

type Empty struct{}

type AccountAccountsOutputItem struct {
	Name  string  `json:"name"`
	Notes float64 `json:"notes"`
}

type AccountAccountsNotAdmin struct{}

type AccountMeOutput struct {
	Name string `json:"name"`
}

type AccountSignInInput struct {
	Name string `json:"name"`
}

type NotesAddNoteInput struct {
	Text string `json:"text"`
}

type Note struct {
	Id     string `json:"id"`
	Text   string `json:"text"`
	Pinned bool   `json:"pinned"`
}

type NotesAddNoteDuplicate struct {
	Text string `json:"text"`
}

type NotesNotesApiOutput struct {
	SignedIn bool   `json:"signedIn"`
	Notes    []Note `json:"notes"`
}

type NotesPinNotesInput struct {
	Ids []string `json:"ids"`
}

type NotesPinNotesOutput struct {
	Count int64 `json:"count"`
}

type NotesRemoveNoteInput struct {
	Id string `json:"id"`
}

type NotesRemoveNoteOutput struct {
	Id string `json:"id"`
}

type NotesRemoveNoteNotFound struct {
	Id string `json:"id"`
}

type NotesRemoveNotesInput struct {
	Ids []string `json:"ids"`
}

type NotesRemoveNotesOutput struct {
	Count int64 `json:"count"`
}

type NotesTogglePinInput struct {
	Id string `json:"id"`
}

type NotesTogglePinNotFound struct {
	Id string `json:"id"`
}

func (e AccountAccountsNotAdmin) Error() string { return "account.accounts: NotAdmin" }
func (e AccountAccountsNotAdmin) failure() (string, string, any) {
	return "account.accounts", "NotAdmin", e
}

func (e NotesAddNoteDuplicate) Error() string { return "notes.addNote: Duplicate" }
func (e NotesAddNoteDuplicate) failure() (string, string, any) {
	return "notes.addNote", "Duplicate", e
}

func (e NotesRemoveNoteNotFound) Error() string { return "notes.removeNote: NotFound" }
func (e NotesRemoveNoteNotFound) failure() (string, string, any) {
	return "notes.removeNote", "NotFound", e
}

func (e NotesTogglePinNotFound) Error() string { return "notes.togglePin: NotFound" }
func (e NotesTogglePinNotFound) failure() (string, string, any) {
	return "notes.togglePin", "NotFound", e
}

// Invalid is the framework error of mutations and endpoints: a message and one message per input field.
type Invalid struct {
	Message string            `json:"message"`
	Fields  map[string]string `json:"fields"`
}

func (e Invalid) Error() string                  { return "Invalid: " + e.Message }
func (e Invalid) failure() (string, string, any) { return "", "Invalid", e }

// Forbidden answers as access does when the visitor may not have it (user-scoped queries and mutations).
type Forbidden struct {
	Message string `json:"message,omitempty"`
}

func (e Forbidden) Error() string                  { return "Forbidden: " + e.Message }
func (e Forbidden) failure() (string, string, any) { return "", "Forbidden", e }

// Ctx is one call. Session is nil when the visitor is signed out or the effect reads no session. Preview is
// true in preview mode; Header holds an endpoint's request headers (no cookie).
type Ctx struct {
	Context context.Context
	Session *Session
	Preview bool
	Header  http.Header
	files   map[string]Upload
	changed bool
	next    *Session
}

// Upload is a file a form sent with the call; Data holds its bytes.
type Upload struct {
	Name string `json:"name"`
	Type string `json:"type"`
	Size int64  `json:"size"`
	Data []byte `json:"data"`
}

// File returns the upload a form field's token names, or nil (mutations and endpoints only).
func (c *Ctx) File(token string) *Upload {
	if f, ok := c.files[token]; ok {
		return &f
	}
	return nil
}

// SetSession signs the visitor in as s (mutations and endpoints only).
func (c *Ctx) SetSession(s Session) { c.changed, c.next = true, &s }

// SignOut ends the visitor's session (mutations and endpoints only).
func (c *Ctx) SignOut() { c.changed, c.next = true, nil }

// Resolvers implements the effects that app.ts lists in remote(). Return a declared error as the error value.
type Resolvers interface {
	// account.accounts (query, with the session); errors: AccountAccountsNotAdmin
	AccountAccounts(ctx *Ctx, in Empty) ([]AccountAccountsOutputItem, error)
	// account.me (query, with the session)
	AccountMe(ctx *Ctx, in Empty) (AccountMeOutput, error)
	// account.signIn (mutation, with the session); may return Invalid
	AccountSignIn(ctx *Ctx, in AccountSignInInput) (Empty, error)
	// account.signOut (mutation, with the session); may return Invalid
	AccountSignOut(ctx *Ctx, in Empty) (Empty, error)
	// notes.addNote (mutation, with the session); errors: NotesAddNoteDuplicate; may return Invalid
	NotesAddNote(ctx *Ctx, in NotesAddNoteInput) (Note, error)
	// notes.listNotes (query, with the session)
	NotesListNotes(ctx *Ctx, in Empty) ([]Note, error)
	// notes.notesApi (endpoint, with the session); may return Invalid
	NotesNotesApi(ctx *Ctx, in Empty) (NotesNotesApiOutput, error)
	// notes.pinNotes (mutation, with the session); may return Invalid
	NotesPinNotes(ctx *Ctx, in NotesPinNotesInput) (NotesPinNotesOutput, error)
	// notes.removeNote (mutation, with the session); errors: NotesRemoveNoteNotFound; may return Invalid
	NotesRemoveNote(ctx *Ctx, in NotesRemoveNoteInput) (NotesRemoveNoteOutput, error)
	// notes.removeNotes (mutation, with the session); may return Invalid
	NotesRemoveNotes(ctx *Ctx, in NotesRemoveNotesInput) (NotesRemoveNotesOutput, error)
	// notes.togglePin (mutation, with the session); errors: NotesTogglePinNotFound; may return Invalid
	NotesTogglePin(ctx *Ctx, in NotesTogglePinInput) (Note, error)
}

// Options configures Handler. Secret (16 characters or more) must equal the x-hozu-secret header of every call:
// the handler trusts the session a call carries, so it answers only the Hozu server.
type Options struct {
	Secret string
}

type failure interface {
	error
	failure() (effect string, name string, data any)
}

type request struct {
	Effect  string            `json:"effect"`
	Input   json.RawMessage   `json:"input"`
	Session *Session          `json:"session"`
	Preview bool              `json:"preview"`
	Headers map[string]string `json:"headers"`
	Files   map[string]Upload `json:"files"`
}

func call[I any, O any](ctx *Ctx, raw json.RawMessage, f func(*Ctx, I) (O, error)) (any, error) {
	var in I
	if err := json.Unmarshal(raw, &in); err != nil {
		return nil, err
	}
	out, err := f(ctx, in)
	return filled(out), err
}

// filled replaces nil slices and maps with empty ones, so a list answers [] and never null.
func filled(v any) any {
	rv := reflect.New(reflect.TypeOf(v)).Elem()
	rv.Set(reflect.ValueOf(v))
	fill(rv)
	return rv.Interface()
}

func fill(v reflect.Value) {
	switch v.Kind() {
	case reflect.Slice:
		if v.IsNil() && v.CanSet() {
			v.Set(reflect.MakeSlice(v.Type(), 0, 0))
		}
		for i := 0; i < v.Len(); i++ {
			fill(v.Index(i))
		}
	case reflect.Map:
		if v.IsNil() && v.CanSet() {
			v.Set(reflect.MakeMap(v.Type()))
		}
	case reflect.Pointer:
		if !v.IsNil() {
			fill(v.Elem())
		}
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			if v.Type().Field(i).IsExported() {
				fill(v.Field(i))
			}
		}
	}
}

// Handler answers the calls of the Hozu server: POST { effect, input, session } → { ok } | { fail } (+ session).
func Handler(r Resolvers, o Options) http.Handler {
	if len(o.Secret) < 16 {
		panic("hozu: Options.Secret must hold the 16 or more characters of the app's remote() secret")
	}
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if req.Method != http.MethodPost {
			http.Error(w, "POST only", http.StatusMethodNotAllowed)
			return
		}
		if subtle.ConstantTimeCompare([]byte(req.Header.Get("X-Hozu-Secret")), []byte(o.Secret)) != 1 {
			http.Error(w, "wrong x-hozu-secret", http.StatusUnauthorized)
			return
		}
		var body request
		if err := json.NewDecoder(req.Body).Decode(&body); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		want := Fingerprint(body.Effect)
		if want == "" {
			http.Error(w, "unknown effect "+body.Effect, http.StatusNotFound)
			return
		}
		if got := req.Header.Get("X-Hozu-Fingerprint"); got != want {
			http.Error(w, body.Effect+" is "+want+" here, not "+got+": run hozu gen and rebuild", http.StatusConflict)
			return
		}
		id := req.Header.Get("X-Hozu-Call")
		ctx := &Ctx{Context: req.Context(), Session: body.Session, Preview: body.Preview, Header: http.Header{}, files: body.Files}
		for k, v := range body.Headers {
			ctx.Header.Set(k, v)
		}
		var out any
		var err error
		switch body.Effect {
		case "account.accounts":
			out, err = call(ctx, body.Input, r.AccountAccounts)
		case "account.me":
			out, err = call(ctx, body.Input, r.AccountMe)
		case "account.signIn":
			out, err = call(ctx, body.Input, r.AccountSignIn)
		case "account.signOut":
			out, err = call(ctx, body.Input, r.AccountSignOut)
		case "notes.addNote":
			out, err = call(ctx, body.Input, r.NotesAddNote)
		case "notes.listNotes":
			out, err = call(ctx, body.Input, r.NotesListNotes)
		case "notes.notesApi":
			out, err = call(ctx, body.Input, r.NotesNotesApi)
		case "notes.pinNotes":
			out, err = call(ctx, body.Input, r.NotesPinNotes)
		case "notes.removeNote":
			out, err = call(ctx, body.Input, r.NotesRemoveNote)
		case "notes.removeNotes":
			out, err = call(ctx, body.Input, r.NotesRemoveNotes)
		case "notes.togglePin":
			out, err = call(ctx, body.Input, r.NotesTogglePin)
		}
		res := map[string]any{}
		var f failure
		switch {
		case err == nil:
			res["ok"] = out
		case errors.As(err, &f):
			effect, name, data := f.failure()
			if effect != "" && effect != body.Effect {
				log.Printf("hozu: %s (call %s) returned %s, an error of %s", body.Effect, id, name, effect)
				http.Error(w, "resolver failed: "+name+" is an error of "+effect, http.StatusInternalServerError)
				return
			}
			res["fail"] = map[string]any{"name": name, "data": data}
		default:
			log.Printf("hozu: %s (call %s): %v", body.Effect, id, err)
			line, _, _ := strings.Cut(err.Error(), "\n")
			http.Error(w, "resolver failed: "+line, http.StatusInternalServerError)
			return
		}
		if ctx.changed {
			res["session"] = ctx.next
		}
		w.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(w).Encode(res); err != nil {
			log.Printf("hozu: %s (call %s): %v", body.Effect, id, err)
		}
	})
}
