export type { BuildOptions, BuildResult } from './build/project.ts'
export { buildProject, UNEXPECTED_ERROR_SCHEMA } from './build/project.ts'
export { hashJson, sha256 } from './canonical/hash.ts'
export type { At } from './canonical/pointer.ts'
export { at, join, parsePointer, pointer, resolveAt, resolveSource } from './canonical/pointer.ts'
export { canonicalStringify } from './canonical/stringify.ts'
export type { CodeInfo } from './ir/codes.ts'
export { codes } from './ir/codes.ts'
export type * from './ir/diagnostic.ts'
export type * from './ir/types.ts'
