import type { DiagnosticCode, Severity } from './diagnostic.ts'

export interface CodeInfo {
  name: string
  severity: Severity
}

export const codes: Record<DiagnosticCode, CodeInfo> = {
  HZ001: { name: 'unreachable-state', severity: 'error' },
  HZ002: { name: 'unhandled-event', severity: 'error' },
  HZ003: { name: 'undeclared-effect', severity: 'error' },
  HZ004: { name: 'unhandled-declared-error', severity: 'error' },
  HZ005: { name: 'illegal-view-event', severity: 'error' },
  HZ006: { name: 'boundary-violation', severity: 'error' },
  HZ007: { name: 'dangling-reference', severity: 'error' },
  HZ008: { name: 'invalid-reference-path', severity: 'error' },
  HZ009: { name: 'shadowed-transition', severity: 'error' },
  HZ010: { name: 'dead-end-state', severity: 'warning' },
  HZ011: { name: 'nondeterministic-build', severity: 'error' },
  HZ012: { name: 'schema-adapter-mismatch', severity: 'error' },
  HZ013: { name: 'duplicate-declaration', severity: 'error' },
  HZ014: { name: 'invalid-builder-output', severity: 'error' },
  HZ015: { name: 'contract-failed', severity: 'error' },
  HZ016: { name: 'uncovered-transition', severity: 'error' },
  HZ017: { name: 'invalid-contract-data', severity: 'error' },
  HZ018: { name: 'behavior-changed-without-contract', severity: 'error' },
  HZ019: { name: 'ineffective-invalidation', severity: 'warning' },
  HZ020: { name: 'user-scope-without-session', severity: 'error' },
  HZ021: { name: 'missing-resolver', severity: 'error' },
  HZ022: { name: 'user-data-in-cacheable-region', severity: 'error' },
  HZ023: { name: 'render-assertion-violated', severity: 'error' },
  HZ024: { name: 'route-mismatch', severity: 'error' },
  HZ025: { name: 'undiscoverable-page', severity: 'warning' },
  HZ026: { name: 'unknown-class', severity: 'error' },
  HZ027: { name: 'invalid-dom-field', severity: 'error' },
  HZ028: { name: 'image-without-dimensions', severity: 'error' },
  HZ029: { name: 'widget-boundary-mismatch', severity: 'error' },
  HZ030: { name: 'unsafe-html', severity: 'error' },
  HZ031: { name: 'invalid-literal', severity: 'error' },
  HZ032: { name: 'untyped-internal-link', severity: 'error' },
  HZ033: { name: 'unchecked-dom-text', severity: 'error' },
  HZ034: { name: 'conflicting-ignore', severity: 'error' },
  HZ035: { name: 'invalid-search-schema', severity: 'error' },
  HZ036: { name: 'form-not-server-runnable', severity: 'warning' },
  HZ037: { name: 'invalid-redirect', severity: 'error' },
  HZ038: { name: 'reserved-header', severity: 'error' },
  HZ039: { name: 'invalid-base-path', severity: 'error' },
  HZ040: { name: 'incomplete-messages', severity: 'error' },
  HZ041: { name: 'message-in-machine', severity: 'error' },
  HZ042: { name: 'invalid-i18n', severity: 'error' },
  HZ043: { name: 'invalid-offline-page', severity: 'error' },
  HZ044: { name: 'untransformed-source', severity: 'error' },
  HZ045: { name: 'incomplete-server-entry', severity: 'warning' },
  HZ046: { name: 'invalid-endpoint', severity: 'error' },
  HZ047: { name: 'fn-not-self-contained', severity: 'error' },
  HZ048: { name: 'invalid-seed', severity: 'error' },
  HZ049: { name: 'cached-user-data', severity: 'error' },
  HZ050: { name: 'live-without-tags', severity: 'error' },
  HZ059: { name: 'reference-escape', severity: 'error' },
  HZ062: { name: 'get-endpoint-invalidates', severity: 'warning' },
}
