import type { DiagnosticCode, Severity } from './diagnostic.ts'

export interface CodeInfo {
  name: string
  severity: Severity
  /** The guide topic that teaches what the code checks (`hozu docs <topic>`). */
  topic: string
  /** What it means, in one line (the source of the diagnostics topic and `hozu docs HZ0xx`, ADR 0053 D). */
  summary: string
  /** The usual fix, in one line. */
  fix: string
}

export const codes: Record<DiagnosticCode, CodeInfo> = {
  HZ001: {
    name: 'unreachable-state',
    severity: 'error',
    topic: 'machine',
    summary: 'state unreachable',
    fix: 'add a transition to it or delete it',
  },
  HZ002: {
    name: 'unhandled-event',
    severity: 'error',
    topic: 'machine',
    summary: 'event handled nowhere',
    fix: 'handle it in a state or remove it',
  },
  HZ003: {
    name: 'undeclared-effect',
    severity: 'error',
    topic: 'data',
    summary: 'unknown effect / reference',
    fix: 'export it from a module the feature lists in `declarations`, or fix the name (the patch suggests one)',
  },
  HZ004: {
    name: 'unhandled-declared-error',
    severity: 'error',
    topic: 'machine',
    summary: 'a declared error is not handled',
    fix: 'add every `failed` key, plus `Unexpected`, in `invoke` and `ui.query`',
  },
  HZ005: {
    name: 'illegal-view-event',
    severity: 'error',
    topic: 'machine',
    summary: 'a node sends an event in a state (without `invoke`) that does not handle it',
    fix: '`ignore: [Event]` in that state, or show the node only via `when`',
  },
  HZ006: {
    name: 'boundary-violation',
    severity: 'error',
    topic: 'feature',
    summary: 'crossing a feature boundary',
    fix: 'import the feature and use its `exports`',
  },
  HZ007: {
    name: 'dangling-reference',
    severity: 'error',
    topic: 'feature',
    summary: 'unknown effect / reference',
    fix: 'export it from a module the feature lists in `declarations`, or fix the name (the patch suggests one)',
  },
  HZ008: {
    name: 'invalid-reference-path',
    severity: 'error',
    topic: 'views',
    summary: 'a path does not exist in the schema',
    fix: 'fix the property name',
  },
  HZ009: {
    name: 'shadowed-transition',
    severity: 'error',
    topic: 'machine',
    summary: 'a guardless transition shadows later ones',
    fix: 'put guarded transitions first',
  },
  HZ010: {
    name: 'dead-end-state',
    severity: 'warning',
    topic: 'machine',
    summary: 'a state has no way out (not final; no `on`, `invoke` or `after`)',
    fix: 'mark it `final: true` or add a transition out of it',
  },
  HZ011: {
    name: 'nondeterministic-build',
    severity: 'error',
    topic: 'feature',
    summary: 'building twice gave different IR',
    fix: 'keep time, randomness and mutable state out of builder callbacks',
  },
  HZ012: {
    name: 'schema-adapter-mismatch',
    severity: 'error',
    topic: 'feature',
    summary: "a schema from another library than the project's adapter",
    fix: "write it with the project's schema library (`project({ schema })`)",
  },
  HZ013: {
    name: 'duplicate-declaration',
    severity: 'error',
    topic: 'feature',
    summary:
      'a declaration registered twice: a second machine (or messages) in a feature, or a name another feature already declares',
    fix: 'keep one; reach the other feature through `imports` and its `exports`',
  },
  HZ014: {
    name: 'invalid-builder-output',
    severity: 'error',
    topic: 'views',
    summary: 'wrong builder output, or a method called on data (`.map`, `.toUpperCase()`)',
    fix: 'follow the builder signature; lists: `ui.each`; computation: a `fn()`',
  },
  HZ015: {
    name: 'contract-failed',
    severity: 'error',
    topic: 'contracts',
    summary: 'a contract fails / contract data does not match its schema',
    fix: 'fix the machine or the contract (decide the intended behaviour first)',
  },
  HZ016: {
    name: 'uncovered-transition',
    severity: 'error',
    topic: 'contracts',
    summary:
      'a transition that decides (guard, `navigate`, a `fn`, comparison or `+ - ?? ?: .length .includes` in a value) has no contract',
    fix: 'add the contract from the snippet',
  },
  HZ017: {
    name: 'invalid-contract-data',
    severity: 'error',
    topic: 'contracts',
    summary: 'a contract fails / contract data does not match its schema',
    fix: 'fix the machine or the contract (decide the intended behaviour first)',
  },
  HZ018: {
    name: 'behavior-changed-without-contract',
    severity: 'error',
    topic: 'contracts',
    summary:
      'a deciding transition changed (fields first, then `was:` / `now:`) and no covering contract fails against the old behaviour',
    fix: 'change or add a contract that specifies the new behaviour; renaming or copying one does not count',
  },
  HZ019: {
    name: 'ineffective-invalidation',
    severity: 'warning',
    topic: 'data',
    summary: '`invalidates` names a tag no query carries',
    fix: 'tag the affected query, or remove the invalidation',
  },
  HZ020: {
    name: 'user-scope-without-session',
    severity: 'error',
    topic: 'auth',
    summary: 'user-scoped data, but the project declares no session',
    fix: 'declare `project({ session })`, or make the query public',
  },
  HZ021: {
    name: 'missing-resolver',
    severity: 'error',
    topic: 'data',
    summary: 'a query, mutation or endpoint without a resolver',
    fix: '`implement(...)` it in the resolvers of `app.ts`',
  },
  HZ022: {
    name: 'user-data-in-cacheable-region',
    severity: 'error',
    topic: 'data',
    summary: 'user data in a cacheable region',
    fix: "keep `scope: 'user'` queries out of cached pages",
  },
  HZ023: {
    name: 'render-assertion-violated',
    severity: 'error',
    topic: 'data',
    summary: "a page's `assert` does not hold for its derived render plan",
    fix: "change the data's scope or freshness, or the assertion",
  },
  HZ024: {
    name: 'route-mismatch',
    severity: 'error',
    topic: 'pages',
    summary:
      'route params mismatch (keys, or a schema that does not fit `:x?`/`:x+`/`:x*`) / page with params but no `entries` (a user-scoped head is private: no sitemap, no warning)',
    fix: 'align them / add `entries`',
  },
  HZ025: {
    name: 'undiscoverable-page',
    severity: 'warning',
    topic: 'pages',
    summary:
      'route params mismatch (keys, or a schema that does not fit `:x?`/`:x+`/`:x*`) / page with params but no `entries` (a user-scoped head is private: no sitemap, no warning)',
    fix: 'align them / add `entries`',
  },
  HZ026: {
    name: 'unknown-class',
    severity: 'error',
    topic: 'views',
    summary: 'a class produces no CSS',
    fix: 'fix the Tailwind class',
  },
  HZ027: {
    name: 'invalid-dom-field',
    severity: 'error',
    topic: 'views',
    summary: 'a DOM field used outside an event, or wrong for this event',
    fix: 'read `ui.dom.*` only in `ui.send` payloads',
  },
  HZ028: {
    name: 'image-without-dimensions',
    severity: 'error',
    topic: 'content',
    summary: '`img` without width/height',
    fix: 'add both',
  },
  HZ029: {
    name: 'component-boundary-mismatch',
    severity: 'error',
    topic: 'components',
    summary: "a client component's module is missing, or a handler for an event it does not emit",
    fix: 'create the module (`hozu add component … --client`); handle declared `emits` only',
  },
  HZ030: {
    name: 'unsafe-html',
    severity: 'error',
    topic: 'views',
    summary: '`ui.html` of untrusted data',
    fix: 'render text instead',
  },
  HZ031: {
    name: 'invalid-literal',
    severity: 'error',
    topic: 'views',
    summary: 'a literal not allowed by its schema',
    fix: 'use an allowed value (the patch suggests one)',
  },
  HZ032: {
    name: 'untyped-internal-link',
    severity: 'error',
    topic: 'views',
    summary: 'internal link or form action written as a string',
    fix: '`ui.link(route, params)` / `ui.link(endpoint)`',
  },
  HZ033: {
    name: 'unchecked-dom-text',
    severity: 'error',
    topic: 'forms',
    summary: 'DOM text into an enum, number or boolean field',
    fix: 'a `<select>`, radios or submit buttons with enum values; in a form, a flag through `ui.dom.formAll` and numbers parsed in the mutation input',
  },
  HZ034: {
    name: 'conflicting-ignore',
    severity: 'error',
    topic: 'machine',
    summary: 'a state both handles and ignores an event',
    fix: 'remove it from one of the two',
  },
  HZ035: {
    name: 'invalid-search-schema',
    severity: 'error',
    topic: 'pages',
    summary: 'search schema is not a flat object of scalars with defaults',
    fix: '`z.object({ key: scalar.default(…) })`',
  },
  HZ036: {
    name: 'form-not-server-runnable',
    severity: 'warning',
    topic: 'forms',
    summary: "a form needs JavaScript: it reads other DOM values, or starts a `runs: 'browser'` mutation",
    fix: "read its values with `ui.dom.form('name')` / `ui.dom.formAll('name')`; a browser mutation needs JS by design",
  },
  HZ037: {
    name: 'invalid-redirect',
    severity: 'error',
    topic: 'http',
    summary: 'a redirect is not a path, hides a page or another redirect, or targets an unknown route',
    fix: 'change or remove the `from` key; point `to` at `ui.link(...)`',
  },
  HZ038: {
    name: 'reserved-header',
    severity: 'error',
    topic: 'http',
    summary: '`http.headers` sets a header the framework owns, or an invalid name/value',
    fix: 'remove it (`cache-control` is derived; CSP is `createServer({ csp })`)',
  },
  HZ039: {
    name: 'invalid-base-path',
    severity: 'error',
    topic: 'http',
    summary: "`basePath` is not `''` or `/segment[/segment…]`",
    fix: "e.g. `'/shop'`, no trailing slash",
  },
  HZ040: {
    name: 'incomplete-messages',
    severity: 'error',
    topic: 'i18n',
    summary: 'a locale lacks a message, or uses other `{placeholders}`',
    fix: 'add/translate the key in that locale',
  },
  HZ041: {
    name: 'message-in-machine',
    severity: 'error',
    topic: 'i18n',
    summary: 'a machine uses a message, `ui.format` or `locale`',
    fix: 'store a code in context; choose the message in the view',
  },
  HZ042: {
    name: 'invalid-i18n',
    severity: 'error',
    topic: 'i18n',
    summary:
      '`site.locales` empty / missing `site.lang` / not a canonical tag, or `ui.alternate` of an undeclared locale',
    fix: "fix the list (`'zh-TW'`, not `'zh_tw'`)",
  },
  HZ043: {
    name: 'invalid-offline-page',
    severity: 'error',
    topic: 'content',
    summary: '`site.offline` has params, no page, or per-request data',
    fix: 'point it at a static page, or remove `offline`',
  },
  HZ044: {
    name: 'untransformed-source',
    severity: 'error',
    topic: 'deploy',
    summary: 'a feature file was loaded without the Hozu transform',
    fix: 'run node with `--import @hozu/transform/register` (`npm start` does), or add `hozuTransform()` to Vite / Vitest',
  },
  HZ045: {
    name: 'invalid-app-module',
    severity: 'error',
    topic: 'deploy',
    summary:
      'no `project({ app })`, its default export is not `app(…)`, or views use client components and `app()` has no bundle',
    fix: '`export default app({ resolvers, components: bundleComponents })`',
  },
  HZ046: {
    name: 'invalid-endpoint',
    severity: 'error',
    topic: 'endpoints',
    summary:
      'an endpoint path is reserved, has params or collides; an error without a status; a form posting to it with another method or an undeclared field',
    fix: 'a static path such as `/api/…` (patch); map every error in `failed`',
  },
  HZ047: {
    name: 'fn-not-self-contained',
    severity: 'error',
    topic: 'data',
    summary: 'a `fn` body uses an imported name or `let` state (it is sent to the browser as source)',
    fix: 'pass the value as input, or write it as a `const` helper in the module',
  },
  HZ048: {
    name: 'invalid-seed',
    severity: 'error',
    topic: 'machine',
    summary:
      '`seed` names a field the context lacks, has no machine or route, or two views on one page seed a machine',
    fix: 'seed top-level context fields, on one view per page',
  },
  HZ049: {
    name: 'cached-user-data',
    severity: 'error',
    topic: 'data',
    summary: "a `scope: 'user'` query is cached (`'static'`, `revalidate`, `swr`)",
    fix: "`freshness: 'request'` (patch), or `'live'` for push",
  },
  HZ050: {
    name: 'live-without-tags',
    severity: 'error',
    topic: 'data',
    summary: "a `'live'` query has no tags",
    fix: "add the tags its writers invalidate, or use `'request'`",
  },
  HZ051: {
    name: 'unmapped-head-error',
    severity: 'error',
    topic: 'pages',
    summary: '`head.failed` misses a declared error of the head query, or maps another one',
    fix: 'choose per error: a route (303), `403`, `404` or `410` (an intent decision: no patch)',
  },
  HZ052: {
    name: 'unserved-route',
    severity: 'error',
    topic: 'pages',
    summary: 'a route that no page renders',
    fix: 'link to the endpoint with `ui.link(endpoint, input)` (patch), or add its `ui.page`',
  },
  HZ053: {
    name: 'html-from-endpoint',
    severity: 'error',
    topic: 'endpoints',
    summary: '(runtime) an endpoint answered `text/html`: a 500',
    fix: 'make it a `ui.page`; statuses and redirects go through `head.failed`',
  },
  HZ054: {
    name: 'single-value-form-read',
    severity: 'error',
    topic: 'forms',
    summary: '`ui.dom.form` reads one value of a list field or of a repeated name',
    fix: "`ui.dom.formAll('name')` (patch)",
  },
  HZ055: {
    name: 'unknown-form-field',
    severity: 'error',
    topic: 'forms',
    summary: 'a form read names no control of the form',
    fix: 'the name it suggests (patch), or add the control',
  },
  HZ056: {
    name: 'submit-button-click',
    severity: 'warning',
    topic: 'forms',
    summary: 'a submit button also sends on click',
    fix: "`name`/`value` on the button, read in submit; or `type: 'button'`",
  },
  HZ057: {
    name: 'lock-out-of-date',
    severity: 'error',
    topic: 'contracts',
    summary:
      '`hozu.lock.json` differs from the computed lock (new, removed or copy-only changes, contract maps, a missing or 0.7 file)',
    fix: 'if intended, `hozu check --update-lock`, then list the accepted `now:` lines in your summary',
  },
  HZ058: {
    name: 'contract-without-decision',
    severity: 'warning',
    topic: 'contracts',
    summary: 'contracts that fire only copy-only transitions and evaluate no guard',
    fix: 'none needed: the lock entries it names review those transitions',
  },
  HZ059: {
    name: 'reference-escape',
    severity: 'error',
    topic: 'views',
    summary:
      'data reached plain JavaScript: a plain helper, a global (`Boolean`, `Object.keys`, `String`…), `typeof`, a spread or `in`',
    fix: 'make the helper a `part()`; for a global use an operator or a `fn()`',
  },
  HZ060: {
    name: 'locale-path-collision',
    severity: 'error',
    topic: 'i18n',
    summary: 'a page route starts with a locale segment (`/de/…` under `site.locales`)',
    fix: 'rename the route (patch); the locale prefix is added for you',
  },
  HZ061: {
    name: 'constrained-form-payload',
    severity: 'warning',
    topic: 'forms',
    summary: 'a form-fed event payload declares limits',
    fix: 'move them to the mutation input',
  },
  HZ062: {
    name: 'get-endpoint-invalidates',
    severity: 'warning',
    topic: 'endpoints',
    summary: 'a GET endpoint declares `invalidates`',
    fix: "`method: 'POST'`, or keep it on purpose (e-mail links)",
  },
  HZ063: {
    name: 'unknown-form-field-opaque',
    severity: 'warning',
    topic: 'forms',
    summary: 'as HZ055, in a form holding `ui.html`, a client component or another view',
    fix: 'as HZ055',
  },
  HZ064: {
    name: 'duplicate-contract',
    severity: 'error',
    topic: 'contracts',
    summary: 'two contracts with identical IR',
    fix: 'remove one (patch)',
  },
  HZ070: {
    name: 'component-closed-render',
    severity: 'error',
    topic: 'components',
    summary: "a component's render references a declaration (event, query, route, message…)",
    fix: 'pass a `Send` through `on`, an `Href` prop, text as a prop or slot',
  },
  HZ071: {
    name: 'variant-from-reference',
    severity: 'error',
    topic: 'components',
    summary: 'a variant from data',
    fix: 'make it a prop, styled through an attribute (`aria-pressed:`, `data-[x=y]:`)',
  },
  HZ072: {
    name: 'owned-property-override',
    severity: 'error',
    topic: 'components',
    summary: "a caller's `class` sets a property the component owns",
    fix: 'declare a variant; a one-off ends with `!` (snippet)',
  },
  HZ073: {
    name: 'important-in-component',
    severity: 'error',
    topic: 'components',
    summary: '`!` inside a component / a leading `!x`',
    fix: 'remove it (patch in the tv config, snippet in the render) / write `x!` (patch)',
  },
  HZ074: {
    name: 'leading-important',
    severity: 'error',
    topic: 'components',
    summary: '`!` inside a component / a leading `!x`',
    fix: 'remove it (patch in the tv config, snippet in the render) / write `x!` (patch)',
  },
  HZ075: {
    name: 'shadowed-inherited-class',
    severity: 'warning',
    topic: 'components',
    summary: "a caller's inherited class (colour, font) is hidden by an inner element",
    fix: 'a variant, or style the inner element',
  },
  HZ076: {
    name: 'component-outer-margin',
    severity: 'warning',
    topic: 'components',
    summary: 'a component owns a margin',
    fix: "remove it (patch); outer spacing is the caller's",
  },
  HZ077: {
    name: 'unneeded-important',
    severity: 'warning',
    topic: 'components',
    summary: '`!` on a property the component does not own',
    fix: 'remove the `!` (patch)',
  },
  HZ078: {
    name: 'variants-config-stale',
    severity: 'error',
    topic: 'components',
    summary: "the kit's `tv.ts` config differs from the design system",
    fix: '`hozu add kit <id> --sync`',
  },
  HZ079: {
    name: 'class-conflict',
    severity: 'error',
    topic: 'components',
    summary: 'two classes of one element set the same property',
    fix: 'the patch: a complementary toggle, or remove the one that never wins',
  },
  HZ080: {
    name: 'shared-part-view',
    severity: 'warning',
    topic: 'components',
    summary: 'a `part()` view inlined by two features',
    fix: 'the snippet: the same `ui.component` in a kit',
  },
  HZ081: {
    name: 'invalid-effect-runtime',
    severity: 'error',
    topic: 'fetch',
    summary:
      "an effect's `runs` and `fetch.ts` disagree: no export, an extra one, a `'server'` effect in it, `'either'` with user data, a Node-only import",
    fix: "export the effect in `fetch.ts`, or `runs: 'server'` with a resolver (`hozu docs fetch`)",
  },
  HZ082: {
    name: 'effect-needs-server',
    severity: 'error',
    topic: 'fetch',
    summary:
      'browser data where only the server can go (a page `head`, `entries`), or a browser mutation invalidating a server-cached tag',
    fix: "the patch: `runs: 'server'`; or `freshness: 'request'` on the cached query",
  },
  HZ083: {
    name: 'undeclared-connect',
    severity: 'warning',
    topic: 'fetch',
    summary:
      "fetch.ts calls an origin (an absolute URL in it) that the feature's `connect` does not list: the browser's CSP blocks it",
    fix: "add the origin to `feature({ connect })` (the fix lists the whole line); `{ env: 'NAME' }` for a URL from public env",
  },
  HZ084: {
    name: 'public-secret',
    severity: 'warning',
    topic: 'env',
    summary:
      'a public env variable named like a secret (`SECRET`, `TOKEN`, `PASSWORD`, `PRIVATE`, `…_KEY`): public values reach the browser',
    fix: 'move it to `env.server`; only a value made to be published (a publishable key) stays public, named `PUBLIC_…`',
  },
  HZ085: {
    name: 'invalid-env-config',
    severity: 'error',
    topic: 'env',
    summary:
      '`env.internal` maps a name that is not a public variable, or to one that is not a server variable',
    fix: 'declare both: the public URL in `env.public`, the internal one in `env.server`',
  },
  HZ086: {
    name: 'env-file-not-ignored',
    severity: 'warning',
    topic: 'env',
    summary: 'an env file listed in `env.files` exists and git does not ignore it',
    fix: 'add it to `.gitignore`; commit `.env.example` (`npx hozu env --example`) instead',
  },
}
