// Generated by scripts/gen-dom.ts. Do not edit.
type V = import('./ui.ts').AttrValue
type NV = Exclude<V, string>
type E<T extends string> = T | NV

export interface HtmlGlobalProps {
  accesskey?: V
  autocapitalize?: E<'off' | 'none' | 'on' | 'sentences' | 'words' | 'characters'>
  autocorrect?: V
  autofocus?: V
  contenteditable?: E<'true' | 'false' | 'plaintext-only'>
  dir?: E<'ltr' | 'rtl' | 'auto'>
  draggable?: E<'true' | 'false'>
  enterkeyhint?: E<'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send'>
  hidden?: E<'hidden' | 'until-found'>
  id?: V
  inert?: V
  inputmode?: E<'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url'>
  itemid?: V
  itemprop?: V
  itemref?: V
  itemscope?: V
  itemtype?: V
  lang?: V
  popover?: E<'auto' | 'manual' | 'hint'>
  role?: V
  spellcheck?: E<'true' | 'false'>
  tabindex?: V
  title?: V
  translate?: E<'yes' | 'no'>
  writingsuggestions?: V
}

export interface SvgGlobalProps {
  'alignment-baseline'?: V
  'baseline-shift'?: V
  'clip-path'?: V
  'clip-rule'?: V
  'color-interpolation'?: V
  'color-interpolation-filters'?: V
  'color-rendering'?: V
  cursor?: V
  direction?: V
  display?: V
  'dominant-baseline'?: V
  fill?: V
  'fill-opacity'?: V
  'fill-rule'?: V
  filter?: V
  'flood-color'?: V
  'flood-opacity'?: V
  'font-family'?: V
  'font-size'?: V
  'font-size-adjust'?: V
  'font-stretch'?: V
  'font-style'?: V
  'font-variant'?: V
  'font-weight'?: V
  id?: V
  'image-rendering'?: V
  lang?: V
  'letter-spacing'?: V
  'lighting-color'?: V
  'marker-end'?: V
  'marker-mid'?: V
  'marker-start'?: V
  mask?: V
  opacity?: V
  overflow?: V
  'paint-order'?: V
  'pointer-events'?: V
  role?: V
  'shape-rendering'?: V
  'stop-color'?: V
  'stop-opacity'?: V
  stroke?: V
  'stroke-dasharray'?: V
  'stroke-dashoffset'?: V
  'stroke-linecap'?: V
  'stroke-linejoin'?: V
  'stroke-miterlimit'?: V
  'stroke-opacity'?: V
  'stroke-width'?: V
  tabindex?: V
  'text-anchor'?: V
  'text-decoration'?: V
  'text-overflow'?: V
  'text-rendering'?: V
  transform?: V
  'unicode-bidi'?: V
  'vector-effect'?: V
  visibility?: V
  'white-space'?: V
  'word-spacing'?: V
  'writing-mode'?: V
}

export interface TagProps {
  a: HtmlGlobalProps & {
    charset?: V
    coords?: V
    download?: V
    href?: V
    hreflang?: V
    name?: V
    ping?: V
    referrerpolicy?: E<
      | 'no-referrer'
      | 'no-referrer-when-downgrade'
      | 'origin'
      | 'origin-when-cross-origin'
      | 'same-origin'
      | 'strict-origin'
      | 'strict-origin-when-cross-origin'
      | 'unsafe-url'
    >
    shape?: V
    target?: V
    type?: V
  }
  abbr: HtmlGlobalProps
  address: HtmlGlobalProps
  area: HtmlGlobalProps & {
    alt?: V
    coords?: V
    download?: V
    href?: V
    hreflang?: V
    ping?: V
    referrerpolicy?: E<
      | 'no-referrer'
      | 'no-referrer-when-downgrade'
      | 'origin'
      | 'origin-when-cross-origin'
      | 'same-origin'
      | 'strict-origin'
      | 'strict-origin-when-cross-origin'
      | 'unsafe-url'
    >
    shape?: E<'circle' | 'default' | 'poly' | 'rect'>
    target?: V
    type?: V
  }
  article: HtmlGlobalProps
  aside: HtmlGlobalProps
  audio: HtmlGlobalProps & {
    autoplay?: V
    controls?: V
    crossorigin?: E<'anonymous' | 'use-credentials'>
    loop?: V
    muted?: V
    preload?: E<'none' | 'metadata' | 'auto'>
    src?: V
  }
  b: HtmlGlobalProps
  bdi: HtmlGlobalProps
  bdo: HtmlGlobalProps
  blockquote: HtmlGlobalProps & {
    cite?: V
  }
  br: HtmlGlobalProps
  button: HtmlGlobalProps & {
    command?: E<
      | 'show-modal'
      | 'close'
      | 'request-close'
      | 'show-popover'
      | 'hide-popover'
      | 'toggle-popover'
      | `--${string}`
    >
    commandfor?: V
    disabled?: V
    form?: V
    formaction?: V
    formenctype?: E<'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain'>
    formmethod?: E<'get' | 'post' | 'dialog'>
    formnovalidate?: V
    formtarget?: V
    name?: V
    popovertarget?: V
    popovertargetaction?: E<'toggle' | 'show' | 'hide'>
    type?: E<'submit' | 'reset' | 'button'>
    value?: V
  }
  canvas: HtmlGlobalProps & {
    height?: V
    width?: V
  }
  caption: HtmlGlobalProps
  cite: HtmlGlobalProps
  code: HtmlGlobalProps
  col: HtmlGlobalProps & {
    span?: V
    width?: V
  }
  colgroup: HtmlGlobalProps & {
    span?: V
    width?: V
  }
  data: HtmlGlobalProps & {
    value?: V
  }
  datalist: HtmlGlobalProps
  dd: HtmlGlobalProps
  del: HtmlGlobalProps & {
    cite?: V
    datetime?: V
  }
  details: HtmlGlobalProps & {
    name?: V
    open?: V
  }
  dfn: HtmlGlobalProps
  dialog: HtmlGlobalProps & {
    closedby?: V
    open?: V
  }
  div: HtmlGlobalProps
  dl: HtmlGlobalProps
  dt: HtmlGlobalProps
  em: HtmlGlobalProps
  embed: HtmlGlobalProps & {
    height?: V
    src?: V
    type?: V
    width?: V
  }
  fieldset: HtmlGlobalProps & {
    disabled?: V
    form?: V
    name?: V
  }
  figcaption: HtmlGlobalProps
  figure: HtmlGlobalProps
  footer: HtmlGlobalProps
  form: HtmlGlobalProps & {
    accept?: V
    'accept-charset'?: V
    action?: V
    autocomplete?: V
    enctype?: E<'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain'>
    method?: E<'get' | 'post' | 'dialog'>
    name?: V
    novalidate?: V
    target?: V
  }
  h1: HtmlGlobalProps
  h2: HtmlGlobalProps
  h3: HtmlGlobalProps
  h4: HtmlGlobalProps
  h5: HtmlGlobalProps
  h6: HtmlGlobalProps
  header: HtmlGlobalProps
  hgroup: HtmlGlobalProps
  hr: HtmlGlobalProps & {
    size?: V
    width?: V
  }
  i: HtmlGlobalProps
  iframe: HtmlGlobalProps & {
    allow?: V
    allowfullscreen?: V
    allowpaymentrequest?: V
    allowusermedia?: V
    height?: V
    loading?: E<'eager' | 'lazy'>
    name?: V
    referrerpolicy?: E<
      | 'no-referrer'
      | 'no-referrer-when-downgrade'
      | 'origin'
      | 'origin-when-cross-origin'
      | 'same-origin'
      | 'strict-origin'
      | 'strict-origin-when-cross-origin'
      | 'unsafe-url'
    >
    sandbox?: V
    src?: V
    width?: V
  }
  img: HtmlGlobalProps & {
    alt?: V
    crossorigin?: E<'anonymous' | 'use-credentials'>
    decoding?: E<'sync' | 'async' | 'auto'>
    fetchpriority?: E<'high' | 'low' | 'auto'>
    height?: V
    ismap?: V
    loading?: E<'eager' | 'lazy'>
    name?: V
    referrerpolicy?: E<
      | 'no-referrer'
      | 'no-referrer-when-downgrade'
      | 'origin'
      | 'origin-when-cross-origin'
      | 'same-origin'
      | 'strict-origin'
      | 'strict-origin-when-cross-origin'
      | 'unsafe-url'
    >
    sizes?: V
    src?: V
    srcset?: V
    usemap?: V
    width?: V
  }
  input: HtmlGlobalProps & {
    accept?: V
    alt?: V
    autocomplete?: V
    checked?: V
    dirname?: V
    disabled?: V
    form?: V
    formaction?: V
    formenctype?: E<'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain'>
    formmethod?: E<'get' | 'post' | 'dialog'>
    formnovalidate?: V
    formtarget?: V
    height?: V
    ismap?: V
    list?: V
    max?: V
    maxlength?: V
    min?: V
    minlength?: V
    multiple?: V
    name?: V
    pattern?: V
    placeholder?: V
    popovertarget?: V
    popovertargetaction?: E<'toggle' | 'show' | 'hide'>
    readonly?: V
    required?: V
    size?: V
    src?: V
    step?: V
    type?: E<
      | 'button'
      | 'checkbox'
      | 'color'
      | 'date'
      | 'datetime-local'
      | 'email'
      | 'file'
      | 'hidden'
      | 'image'
      | 'month'
      | 'number'
      | 'password'
      | 'radio'
      | 'range'
      | 'reset'
      | 'search'
      | 'submit'
      | 'tel'
      | 'text'
      | 'time'
      | 'url'
      | 'week'
    >
    usemap?: V
    value?: V
    width?: V
  }
  ins: HtmlGlobalProps & {
    cite?: V
    datetime?: V
  }
  kbd: HtmlGlobalProps
  label: HtmlGlobalProps & {
    for?: V
    form?: V
  }
  legend: HtmlGlobalProps
  li: HtmlGlobalProps & {
    type?: V
    value?: V
  }
  main: HtmlGlobalProps
  map: HtmlGlobalProps & {
    name?: V
  }
  mark: HtmlGlobalProps
  menu: HtmlGlobalProps
  meter: HtmlGlobalProps & {
    high?: V
    low?: V
    max?: V
    min?: V
    optimum?: V
    value?: V
  }
  nav: HtmlGlobalProps
  noscript: HtmlGlobalProps
  object: HtmlGlobalProps & {
    data?: V
    form?: V
    height?: V
    name?: V
    type?: V
    typemustmatch?: V
    usemap?: V
    width?: V
  }
  ol: HtmlGlobalProps & {
    reversed?: V
    start?: V
    type?: E<'1' | 'a' | 'A' | 'i' | 'I'>
  }
  optgroup: HtmlGlobalProps & {
    disabled?: V
    label?: V
  }
  option: HtmlGlobalProps & {
    disabled?: V
    label?: V
    selected?: V
    value?: V
  }
  output: HtmlGlobalProps & {
    for?: V
    form?: V
    name?: V
  }
  p: HtmlGlobalProps
  picture: HtmlGlobalProps
  pre: HtmlGlobalProps & {
    width?: V
  }
  progress: HtmlGlobalProps & {
    max?: V
    value?: V
  }
  q: HtmlGlobalProps & {
    cite?: V
  }
  rp: HtmlGlobalProps
  rt: HtmlGlobalProps
  ruby: HtmlGlobalProps
  s: HtmlGlobalProps
  samp: HtmlGlobalProps
  search: HtmlGlobalProps
  section: HtmlGlobalProps
  select: HtmlGlobalProps & {
    autocomplete?: V
    disabled?: V
    form?: V
    multiple?: V
    name?: V
    required?: V
    size?: V
  }
  small: HtmlGlobalProps
  source: HtmlGlobalProps & {
    height?: V
    media?: V
    sizes?: V
    src?: V
    srcset?: V
    type?: V
    width?: V
  }
  span: HtmlGlobalProps
  strong: HtmlGlobalProps
  sub: HtmlGlobalProps
  summary: HtmlGlobalProps
  sup: HtmlGlobalProps
  table: HtmlGlobalProps & {
    frame?: V
    width?: V
  }
  tbody: HtmlGlobalProps
  td: HtmlGlobalProps & {
    abbr?: V
    colspan?: V
    headers?: V
    height?: V
    rowspan?: V
    scope?: V
    width?: V
  }
  textarea: HtmlGlobalProps & {
    autocomplete?: V
    cols?: V
    dirname?: V
    disabled?: V
    form?: V
    maxlength?: V
    minlength?: V
    name?: V
    placeholder?: V
    readonly?: V
    required?: V
    rows?: V
    value?: V
    wrap?: E<'soft' | 'hard'>
  }
  tfoot: HtmlGlobalProps
  th: HtmlGlobalProps & {
    abbr?: V
    colspan?: V
    headers?: V
    height?: V
    rowspan?: V
    scope?: E<'row' | 'col' | 'rowgroup' | 'colgroup'>
    width?: V
  }
  thead: HtmlGlobalProps
  time: HtmlGlobalProps & {
    datetime?: V
  }
  tr: HtmlGlobalProps
  track: HtmlGlobalProps & {
    default?: V
    kind?: E<'subtitles' | 'captions' | 'descriptions' | 'chapters' | 'metadata'>
    label?: V
    src?: V
    srclang?: V
  }
  u: HtmlGlobalProps
  ul: HtmlGlobalProps & {
    type?: V
  }
  var: HtmlGlobalProps
  video: HtmlGlobalProps & {
    autoplay?: V
    controls?: V
    crossorigin?: E<'anonymous' | 'use-credentials'>
    height?: V
    loop?: V
    muted?: V
    playsinline?: V
    poster?: V
    preload?: E<'none' | 'metadata' | 'auto'>
    src?: V
    width?: V
  }
  wbr: HtmlGlobalProps
  svg: SvgGlobalProps & {
    height?: V
    playbackOrder?: V
    preserveAspectRatio?: V
    syncBehaviorDefault?: V
    syncToleranceDefault?: V
    systemLanguage?: V
    timelineBegin?: V
    viewBox?: V
    width?: V
    x?: V
    xmlns?: V
    y?: V
  }
  animate: SvgGlobalProps & {
    accumulate?: V
    additive?: V
    attributeName?: V
    attributeType?: V
    begin?: V
    by?: V
    calcMode?: V
    dur?: V
    end?: V
    from?: V
    href?: V
    keySplines?: V
    keyTimes?: V
    max?: V
    min?: V
    repeatCount?: V
    repeatDur?: V
    restart?: V
    systemLanguage?: V
    to?: V
    values?: V
  }
  animateMotion: SvgGlobalProps & {
    accumulate?: V
    additive?: V
    begin?: V
    by?: V
    calcMode?: V
    dur?: V
    end?: V
    from?: V
    href?: V
    keyPoints?: V
    keySplines?: V
    keyTimes?: V
    max?: V
    min?: V
    origin?: V
    path?: V
    repeatCount?: V
    repeatDur?: V
    restart?: V
    rotate?: V
    systemLanguage?: V
    to?: V
    values?: V
  }
  animateTransform: SvgGlobalProps & {
    accumulate?: V
    additive?: V
    attributeName?: V
    attributeType?: V
    begin?: V
    by?: V
    calcMode?: V
    dur?: V
    end?: V
    from?: V
    href?: V
    keySplines?: V
    keyTimes?: V
    max?: V
    min?: V
    repeatCount?: V
    repeatDur?: V
    restart?: V
    systemLanguage?: V
    to?: V
    type?: V
    values?: V
  }
  circle: SvgGlobalProps & {
    cx?: V
    cy?: V
    pathLength?: V
    r?: V
    systemLanguage?: V
  }
  clipPath: SvgGlobalProps & {
    clipPathUnits?: V
    systemLanguage?: V
  }
  defs: SvgGlobalProps & {
    systemLanguage?: V
  }
  desc: SvgGlobalProps & {
    systemLanguage?: V
  }
  ellipse: SvgGlobalProps & {
    cx?: V
    cy?: V
    pathLength?: V
    rx?: V
    ry?: V
    systemLanguage?: V
  }
  feBlend: SvgGlobalProps & {
    height?: V
    in?: V
    in2?: V
    mode?: V
    result?: V
    width?: V
    x?: V
    y?: V
  }
  feColorMatrix: SvgGlobalProps & {
    height?: V
    in?: V
    result?: V
    type?: V
    values?: V
    width?: V
    x?: V
    y?: V
  }
  feComponentTransfer: SvgGlobalProps & {
    height?: V
    in?: V
    result?: V
    width?: V
    x?: V
    y?: V
  }
  feComposite: SvgGlobalProps & {
    height?: V
    in?: V
    in2?: V
    k1?: V
    k2?: V
    k3?: V
    k4?: V
    operator?: V
    result?: V
    width?: V
    x?: V
    y?: V
  }
  feConvolveMatrix: SvgGlobalProps & {
    bias?: V
    divisor?: V
    edgeMode?: V
    height?: V
    in?: V
    kernelMatrix?: V
    kernelUnitLength?: V
    order?: V
    preserveAlpha?: V
    result?: V
    targetX?: V
    targetY?: V
    width?: V
    x?: V
    y?: V
  }
  feDiffuseLighting: SvgGlobalProps & {
    diffuseConstant?: V
    height?: V
    in?: V
    kernelUnitLength?: V
    result?: V
    surfaceScale?: V
    width?: V
    x?: V
    y?: V
  }
  feDisplacementMap: SvgGlobalProps & {
    height?: V
    in?: V
    in2?: V
    result?: V
    scale?: V
    width?: V
    x?: V
    xChannelSelector?: V
    y?: V
    yChannelSelector?: V
  }
  feDistantLight: SvgGlobalProps & {
    azimuth?: V
    elevation?: V
  }
  feDropShadow: SvgGlobalProps & {
    dx?: V
    dy?: V
    height?: V
    in?: V
    result?: V
    stdDeviation?: V
    width?: V
    x?: V
    y?: V
  }
  feFlood: SvgGlobalProps & {
    height?: V
    result?: V
    width?: V
    x?: V
    y?: V
  }
  feFuncA: SvgGlobalProps & {
    amplitude?: V
    exponent?: V
    intercept?: V
    offset?: V
    slope?: V
    tableValues?: V
    type?: V
  }
  feFuncB: SvgGlobalProps & {
    amplitude?: V
    exponent?: V
    intercept?: V
    offset?: V
    slope?: V
    tableValues?: V
    type?: V
  }
  feFuncG: SvgGlobalProps & {
    amplitude?: V
    exponent?: V
    intercept?: V
    offset?: V
    slope?: V
    tableValues?: V
    type?: V
  }
  feFuncR: SvgGlobalProps & {
    amplitude?: V
    exponent?: V
    intercept?: V
    offset?: V
    slope?: V
    tableValues?: V
    type?: V
  }
  feGaussianBlur: SvgGlobalProps & {
    edgeMode?: V
    height?: V
    in?: V
    result?: V
    stdDeviation?: V
    width?: V
    x?: V
    y?: V
  }
  feImage: SvgGlobalProps & {
    crossorigin?: V
    height?: V
    href?: V
    preserveAspectRatio?: V
    result?: V
    width?: V
    x?: V
    y?: V
  }
  feMerge: SvgGlobalProps & {
    height?: V
    result?: V
    width?: V
    x?: V
    y?: V
  }
  feMergeNode: SvgGlobalProps & {
    in?: V
  }
  feMorphology: SvgGlobalProps & {
    height?: V
    in?: V
    operator?: V
    radius?: V
    result?: V
    width?: V
    x?: V
    y?: V
  }
  feOffset: SvgGlobalProps & {
    dx?: V
    dy?: V
    height?: V
    in?: V
    result?: V
    width?: V
    x?: V
    y?: V
  }
  fePointLight: SvgGlobalProps & {
    x?: V
    y?: V
    z?: V
  }
  feSpecularLighting: SvgGlobalProps & {
    height?: V
    in?: V
    kernelUnitLength?: V
    result?: V
    specularConstant?: V
    specularExponent?: V
    surfaceScale?: V
    width?: V
    x?: V
    y?: V
  }
  feSpotLight: SvgGlobalProps & {
    limitingConeAngle?: V
    pointsAtX?: V
    pointsAtY?: V
    pointsAtZ?: V
    specularExponent?: V
    x?: V
    y?: V
    z?: V
  }
  feTile: SvgGlobalProps & {
    height?: V
    in?: V
    result?: V
    width?: V
    x?: V
    y?: V
  }
  feTurbulence: SvgGlobalProps & {
    baseFrequency?: V
    height?: V
    numOctaves?: V
    result?: V
    seed?: V
    stitchTiles?: V
    type?: V
    width?: V
    x?: V
    y?: V
  }
  filter: SvgGlobalProps & {
    filterRes?: V
    filterUnits?: V
    height?: V
    href?: V
    primitiveUnits?: V
    width?: V
    x?: V
    y?: V
  }
  foreignObject: SvgGlobalProps & {
    height?: V
    systemLanguage?: V
    width?: V
    x?: V
    y?: V
  }
  g: SvgGlobalProps & {
    systemLanguage?: V
  }
  image: SvgGlobalProps & {
    crossorigin?: V
    height?: V
    href?: V
    preserveAspectRatio?: V
    systemLanguage?: V
    type?: V
    width?: V
    x?: V
    y?: V
  }
  line: SvgGlobalProps & {
    pathLength?: V
    systemLanguage?: V
    x1?: V
    x2?: V
    y1?: V
    y2?: V
  }
  linearGradient: SvgGlobalProps & {
    gradientTransform?: V
    gradientUnits?: V
    href?: V
    spreadMethod?: V
    x1?: V
    x2?: V
    y1?: V
    y2?: V
  }
  marker: SvgGlobalProps & {
    markerHeight?: V
    markerUnits?: V
    markerWidth?: V
    orient?: V
    preserveAspectRatio?: V
    refX?: V
    refY?: V
    viewBox?: V
  }
  mask: SvgGlobalProps & {
    height?: V
    maskContentUnits?: V
    maskUnits?: V
    systemLanguage?: V
    width?: V
    x?: V
    y?: V
  }
  metadata: SvgGlobalProps & {
    systemLanguage?: V
  }
  mpath: SvgGlobalProps & {
    href?: V
  }
  path: SvgGlobalProps & {
    d?: V
    pathLength?: V
    systemLanguage?: V
  }
  pattern: SvgGlobalProps & {
    height?: V
    href?: V
    patternContentUnits?: V
    patternTransform?: V
    patternUnits?: V
    preserveAspectRatio?: V
    systemLanguage?: V
    viewBox?: V
    width?: V
    x?: V
    y?: V
  }
  polygon: SvgGlobalProps & {
    pathLength?: V
    points?: V
    systemLanguage?: V
  }
  polyline: SvgGlobalProps & {
    pathLength?: V
    points?: V
    systemLanguage?: V
  }
  radialGradient: SvgGlobalProps & {
    cx?: V
    cy?: V
    fr?: V
    fx?: V
    fy?: V
    gradientTransform?: V
    gradientUnits?: V
    href?: V
    r?: V
    spreadMethod?: V
  }
  rect: SvgGlobalProps & {
    height?: V
    pathLength?: V
    rx?: V
    ry?: V
    systemLanguage?: V
    width?: V
    x?: V
    y?: V
  }
  set: SvgGlobalProps & {
    attributeName?: V
    attributeType?: V
    begin?: V
    dur?: V
    end?: V
    href?: V
    max?: V
    min?: V
    repeatCount?: V
    repeatDur?: V
    restart?: V
    systemLanguage?: V
    to?: V
  }
  stop: SvgGlobalProps & {
    offset?: V
  }
  switch: SvgGlobalProps & {
    systemLanguage?: V
  }
  symbol: SvgGlobalProps & {
    height?: V
    preserveAspectRatio?: V
    refX?: V
    refY?: V
    viewBox?: V
    width?: V
    x?: V
    y?: V
  }
  text: SvgGlobalProps & {
    dx?: V
    dy?: V
    editable?: V
    lengthAdjust?: V
    rotate?: V
    systemLanguage?: V
    textLength?: V
    x?: V
    y?: V
  }
  textPath: SvgGlobalProps & {
    href?: V
    lengthAdjust?: V
    method?: V
    path?: V
    side?: V
    spacing?: V
    startOffset?: V
    systemLanguage?: V
    textLength?: V
  }
  tspan: SvgGlobalProps & {
    dx?: V
    dy?: V
    lengthAdjust?: V
    rotate?: V
    systemLanguage?: V
    textLength?: V
    x?: V
    y?: V
  }
  use: SvgGlobalProps & {
    height?: V
    href?: V
    systemLanguage?: V
    width?: V
    x?: V
    y?: V
  }
  view: SvgGlobalProps & {
    preserveAspectRatio?: V
    viewBox?: V
    viewTarget?: V
  }
}
