import { readFileSync } from 'node:fs'
import { basename } from 'node:path'
import { fileURLToPath } from 'node:url'

export type Runner = 'pnpm exec' | 'npx' | 'yarn' | 'bunx'

export const RUNNERS: readonly Runner[] = ['pnpm exec', 'npx', 'yarn', 'bunx']

export const BEGIN = '<!-- hozu: generated by hozu skill; edits between these markers are replaced -->'
export const END = '<!-- /hozu -->'

export const TARGETS = [
  { guide: 'CLAUDE.md', skill: '.claude/skills/hozu', read: 'Use the `hozu` skill (`__SKILL__/SKILL.md`).' },
  {
    guide: 'AGENTS.md',
    skill: '.agents/skills/hozu',
    read: 'Read `__SKILL__/SKILL.md` before writing or changing any Hozu code.',
  },
] as const

export type Target = (typeof TARGETS)[number]

const fill = (text: string, values: Record<string, string>) =>
  Object.entries(values).reduce((out, [key, value]) => out.replaceAll(`__${key}__`, value), text)

const note = (runner: Runner, skillRunner: Runner) =>
  runner === skillRunner
    ? ''
    : `\nThe skill writes commands as \`${skillRunner} …\`; in this app use \`${runner} …\`.\n`

function filled(template: string, target: Target, name: string, runner: Runner, skillRunner: Runner) {
  return fill(fill(template, { READ: target.read }), {
    NAME: name,
    RUN: runner,
    SKILL: target.skill,
    NOTE: note(runner, skillRunner),
  })
}

export function currentGuide(): string {
  return readFileSync(fileURLToPath(new URL('../templates/guide.md', import.meta.url)), 'utf8')
}

/** The 0.8 guide for one target, between the markers. */
export const guideBlock = (target: Target, name: string, runner: Runner, template = currentGuide()) =>
  `${BEGIN}\n${filled(template, target, name, runner, 'npx').trimEnd()}\n${END}\n`

export type BlockResult =
  | { kind: 'replaced' | 'written' | 'current'; code: string }
  | { kind: 'custom'; block: string }

/** The new Hozu block of a CLAUDE.md / AGENTS.md, between markers; a file without markers is `custom`. */
export function migrateGuide(
  existing: string | null,
  target: Target,
  dir: string,
  runner: Runner,
  template = currentGuide(),
): BlockResult {
  const begin = existing?.indexOf(BEGIN) ?? -1
  const end = existing?.indexOf(END) ?? -1
  const own = begin >= 0 && end > begin ? existing!.slice(begin, end) : existing
  const name = own?.match(/^# (.+)$/m)?.[1] ?? basename(dir)
  const detected = RUNNERS.find((r) => own?.includes(`${r} hozu `)) ?? runner
  const block = guideBlock(target, name, detected, template)
  if (existing === null) return { kind: 'written', code: block }
  if (begin >= 0 && end > begin) {
    const code = existing.slice(0, begin) + block + existing.slice(end + END.length).replace(/^\n/, '')
    return { kind: code === existing ? 'current' : 'replaced', code }
  }
  return { kind: 'custom', block }
}
