import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { htmlElementAttributes as html } from 'html-element-attributes'
import { svgElementAttributes as svg } from 'svg-element-attributes'

const out = fileURLToPath(new URL('../packages/core/src/ir/dom-data.ts', import.meta.url))
const propsOut = fileURLToPath(new URL('../packages/core/src/builders/dom-props.ts', import.meta.url))

export const htmlTags =
  `a abbr address area article aside audio b bdi bdo blockquote br button canvas caption cite
code col colgroup data datalist dd del details dfn dialog div dl dt em embed fieldset figcaption figure footer form
h1 h2 h3 h4 h5 h6 header hgroup hr i iframe img input ins kbd label legend li main map mark menu meter nav object ol
optgroup option output p picture pre progress q rp rt ruby s samp search section select small source span strong sub
summary sup table tbody td textarea tfoot th thead time tr track u ul var video wbr`.split(/\s+/)

export const svgTags = `svg animate animateMotion animateTransform circle clipPath defs desc ellipse feBlend
feColorMatrix feComponentTransfer feComposite feConvolveMatrix feDiffuseLighting feDisplacementMap feDistantLight
feDropShadow feFlood feFuncA feFuncB feFuncG feFuncR feGaussianBlur feImage feMerge feMergeNode feMorphology feOffset
fePointLight feSpecularLighting feSpotLight feTile feTurbulence filter foreignObject g image line linearGradient
marker mask metadata mpath path pattern polygon polyline radialGradient rect set stop switch symbol text textPath
tspan use view`.split(/\s+/)

const voids = 'area br col embed hr img input source track wbr'.split(' ')

const excluded = new Set(
  `class style nonce is slot part exportparts srcdoc align alink archive axis background bgcolor border cellpadding
cellspacing char charoff classid clear codebase codetype color compact declare face frameborder hspace link
longdesc marginheight marginwidth nohref noshade nowrap profile rev rules scheme scrolling standby summary valign
valuetype version vlink vspace datafld dataformatas datasrc language event alpha colorspace code about datatype
property resource typeof content rel externalResourcesRequired requiredFeatures requiredExtensions requiredFonts
requiredFormats focusable focusHighlight enable-background kerning glyph-orientation-horizontal
glyph-orientation-vertical clip color-profile baseProfile contentScriptType contentStyleType zoomAndPan version
xlink:href xlink:title xlink:show xlink:actuate xlink:type xlink:role xlink:arcrole xml:space xml:base xml:lang
externalresourcesrequired playbackorder timelinebegin snapshotTime`.split(/\s+/),
)
const keep = (a: string) => !excluded.has(a) && !a.startsWith('nav-') && !a.startsWith('on')

const globalHtml = [...html['*']!.filter(keep), 'role'].sort()
const presentation = svg['*']!.filter(keep).sort()
const presentationSet = new Set(presentation)

const attrs: Record<string, string[]> = {}
for (const tag of htmlTags) attrs[tag] = (html[tag] ?? []).filter(keep).sort()
attrs.textarea = [...attrs.textarea!, 'value'].sort()
for (const tag of svgTags) {
  const own = (svg[tag] ?? []).filter((a) => keep(a) && !presentationSet.has(a))
  if (
    [
      'image',
      'use',
      'feImage',
      'textPath',
      'mpath',
      'pattern',
      'linearGradient',
      'radialGradient',
      'filter',
    ].includes(tag)
  )
    own.push('href')
  if (tag === 'svg') own.push('xmlns')
  attrs[tag] = [...new Set(own)].sort()
}

const list = (xs: string[]) => `[${xs.map((x) => `'${x}'`).join(', ')}]`
const body = `// Generated by scripts/gen-dom.ts from html-element-attributes and svg-element-attributes. Do not edit.
export const htmlTags = ${list(htmlTags)} as const
export const svgTags = ${list(svgTags)} as const
export const voidTags = ${list(voids)} as const
export const htmlGlobalAttrs = ${list(globalHtml)} as const
export const svgGlobalAttrs = ${list(presentation)} as const
export const tagAttrs = {
${[...htmlTags, ...svgTags].map((t) => `  ${/^[a-z][a-zA-Z0-9]*$/.test(t) ? t : `'${t}'`}: ${list(attrs[t]!)},`).join('\n')}
} as const
`
writeFileSync(out, body)

const key = (a: string) => (/^[A-Za-z_][A-Za-z0-9_]*$/.test(a) ? a : `'${a}'`)
const members = (xs: string[]) => xs.map((a) => `  ${key(a)}?: V`).join('\n')
const props = `// Generated by scripts/gen-dom.ts. Do not edit.
type V = import('./ui.ts').AttrValue

export interface HtmlGlobalProps {
${members(globalHtml)}
}

export interface SvgGlobalProps {
${members(presentation)}
}

export interface TagProps {
${[...htmlTags, ...svgTags]
  .map(
    (t) =>
      `  ${key(t)}: ${svgTags.includes(t) ? 'SvgGlobalProps' : 'HtmlGlobalProps'}${attrs[t]!.length ? ` & {\n${attrs[t]!.map((a) => `    ${key(a)}?: V`).join('\n')}\n  }` : ''}`,
  )
  .join('\n')}
}
`
writeFileSync(propsOut, props)
