/** What the project's Tailwind design system adds to Tailwind's defaults (`designTokens` in `@hozu/css`). */
export interface DesignTokens {
  theme: string[]
  utilities: string[]
  functional: string[]
}

type ClassGroup = string | Record<string, ((value: string) => boolean)[]>

export interface TwMergeConfig {
  extend: { theme: Record<string, string[]>; classGroups: Record<string, ClassGroup[]> }
}

const SCALES: [prefix: string, scale: string][] = (
  [
    ['--animate-', 'animate'],
    ['--aspect-', 'aspect'],
    ['--blur-', 'blur'],
    ['--breakpoint-', 'breakpoint'],
    ['--color-', 'color'],
    ['--container-', 'container'],
    ['--drop-shadow-', 'drop-shadow'],
    ['--ease-', 'ease'],
    ['--font-', 'font'],
    ['--font-weight-', 'font-weight'],
    ['--inset-shadow-', 'inset-shadow'],
    ['--leading-', 'leading'],
    ['--perspective-', 'perspective'],
    ['--radius-', 'radius'],
    ['--shadow-', 'shadow'],
    ['--spacing-', 'spacing'],
    ['--text-', 'text'],
    ['--text-shadow-', 'text-shadow'],
    ['--tracking-', 'tracking'],
  ] as [string, string][]
).sort(([a], [b]) => b.length - a.length)

const anyValue = (value: string) => value !== ''

/** Maps `@theme` namespaces to tailwind-merge theme scales and `@utility` names to their own class groups. */
export function twMergeConfigOf(tokens: DesignTokens): TwMergeConfig {
  const theme: Record<string, Set<string>> = {}
  for (const key of tokens.theme) {
    const hit = SCALES.find(([prefix]) => key.startsWith(prefix))
    if (!hit) continue
    const name = key.slice(hit[0].length)
    if (!name || name.includes('--')) continue
    theme[hit[1]] ??= new Set()
    theme[hit[1]]!.add(name)
  }
  const classGroups: Record<string, ClassGroup[]> = {}
  for (const name of [...new Set(tokens.utilities)].sort()) classGroups[name] = [name]
  for (const name of [...new Set(tokens.functional)].sort())
    classGroups[name] = [...(classGroups[name] ?? []), { [name]: [anyValue] }]
  return {
    extend: {
      theme: Object.fromEntries(
        Object.keys(theme)
          .sort()
          .map((k) => [k, [...theme[k]!].sort()]),
      ),
      classGroups,
    },
  }
}

const key = (k: string) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : `'${k}'`)
const str = (s: string) => `'${s.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`

function list(items: string[], indent: string, prefix: string): string {
  const line = `[${items.join(', ')}]`
  if (indent.length + prefix.length + line.length + 1 <= 110) return line
  return `[\n${items.map((i) => `${indent}  ${i},`).join('\n')}\n${indent}]`
}

const group = (g: ClassGroup) =>
  typeof g === 'string'
    ? str(g)
    : `{ ${Object.keys(g)
        .map((k) => `${key(k)}: [(value: string) => value !== '']`)
        .join(', ')} }`

function objectOf(entries: [string, string[]][], indent: string): string {
  if (!entries.length) return '{}'
  const body = entries.map(
    ([k, items]) => `${indent}  ${key(k)}: ${list(items, `${indent}  `, `${key(k)}: `)},`,
  )
  return `{\n${body.join('\n')}\n${indent}}`
}

export const START = (kit: string) => `// hozu:variants-config ${kit}`
export const END = '// /hozu:variants-config'

/** The marked block of `<kit>/tv.ts`, regenerated by `hozu add kit <kit> --sync`. */
export function configBlock(kit: string, config: TwMergeConfig): string {
  const theme = objectOf(
    Object.entries(config.extend.theme).map(([k, v]) => [k, v.map(str)]),
    '    ',
  )
  const groups = objectOf(
    Object.entries(config.extend.classGroups).map(([k, v]) => [k, v.map(group)]),
    '    ',
  )
  return `${START(kit)}\nconst twMergeConfig = {\n  extend: {\n    theme: ${theme},\n    classGroups: ${groups},\n  },\n}\n${END}`
}

export const tvModule = (kit: string, config: TwMergeConfig) =>
  `import { createTV } from '@hozu/variants'\n\n${configBlock(kit, config)}\n\nexport const tv = createTV({ twMergeConfig })\n`

const blockAt = (source: string, kit: string) => {
  const start = source.indexOf(START(kit))
  if (start < 0) return null
  const end = source.indexOf(END, start)
  return end < 0 ? null : { start, end: end + END.length }
}

const normalize = (text: string) =>
  text
    .replace(/\s+/g, '')
    .replaceAll('"', "'")
    .replace(/,(?=[}\]])/g, '')

/** `'current'`, `'stale'`, or `'none'` when the file has no marked block for this kit. */
export function configStatus(
  source: string,
  kit: string,
  config: TwMergeConfig,
): 'current' | 'stale' | 'none' {
  const at = blockAt(source, kit)
  if (!at) return 'none'
  return normalize(source.slice(at.start, at.end)) === normalize(configBlock(kit, config))
    ? 'current'
    : 'stale'
}

/** Rewrites only the marked block; `null` when the file has none. */
export function syncConfig(source: string, kit: string, config: TwMergeConfig): string | null {
  const at = blockAt(source, kit)
  return at ? source.slice(0, at.start) + configBlock(kit, config) + source.slice(at.end) : null
}

export const configLine = (source: string, kit: string) => {
  const at = blockAt(source, kit)
  return at ? source.slice(0, at.start).split('\n').length : null
}
